### ISSUE TITLE
RCTAsyncLocalStorage.multiGet() not found

### ISSUE THREAD

**Issue by rturk** [michaelcontento/redux-storage-engine-reactnativeasyncstorage#5]
Hi If I try to use the React Native Storage engine in conjunction with filter (redux-storage-decorator-filter') I get the following error:

Unhandled JS Exception: Callback with id 1: RCTAsyncLocalStorage.multiGet() not found

**Comment by michaelcontento** [comment]
Hi, can you share the stack trace of this error, please? 

Because neither this or `redux-storage-decorator-filter` do call `multiGet` at all! [getItem](https://github.com/michaelcontento/redux-storage-engine-reactnativeasyncstorage/blob/master/src/index.js#L5) and [setItem](https://github.com/michaelcontento/redux-storage-engine-reactnativeasyncstorage/blob/master/src/index.js#L11) are the only called methods of [AsyncStorage](https://github.com/michaelcontento/redux-storage-engine-reactnativeasyncstorage/blob/master/src/index.js#L1).

**Comment by rturk** [comment]
Hi
Its hard to track this. I've upgraded to RN 0.21 and replaced thunk for Sags. I don't have this bug anymore.
Closing this for now.

**Comment by wv1124** [comment]
npm update & npm install can solve this problem
